# Generated by Django 6.1 on 2026-09-30 12:19

from django.db import migrations, models


def add_initial_english_product_copy(apps, schema_editor):
    Product = apps.get_model("store", "Product")
    translations = {
        "الورد الجوري": (
            "Rose Musk",
            "Soft rose notes blend with musk for a light, elegant scent.",
        ),
        "عنبر الليل": (
            "Night Amber",
            "Warm amber and oud meet soft wood notes for evenings and special occasions.",
        ),
        "مسك أبيض": (
            "White Musk",
            "Clean, soft musk with light floral notes for everyday use.",
        ),
        "عود المساء": (
            "Evening Oud",
            "A rich scent with oud wood, amber, and warm spices.",
        ),
        "نسيم الحمضيات": (
            "Citrus Breeze",
            "Fresh bergamot and citrus with a light wood base for a bright start to the day.",
        ),
    }
    for arabic_name, (english_name, english_description) in translations.items():
        Product.objects.filter(name=arabic_name, name_en="").update(
            name_en=english_name,
            description_en=english_description,
        )


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0002_cart_orders_and_stock"),
    ]

    operations = [
        migrations.CreateModel(
            name="StoreContent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "hero_title_ar",
                    models.CharField(
                        default="عطرك يروي قصتك.",
                        max_length=180,
                        verbose_name="عنوان الواجهة بالعربية",
                    ),
                ),
                (
                    "hero_title_en",
                    models.CharField(
                        default="Your scent. Your signature.",
                        max_length=180,
                        verbose_name="Hero title in English",
                    ),
                ),
                (
                    "hero_description_ar",
                    models.TextField(
                        default="اكتشف مجموعة مختارة من العطور الراقية التي تجمع بين الأناقة والأصالة والحضور المميز.",
                        verbose_name="وصف الواجهة بالعربية",
                    ),
                ),
                (
                    "hero_description_en",
                    models.TextField(
                        default="Discover refined fragrances selected for elegance, character and an unforgettable presence.",
                        verbose_name="Hero description in English",
                    ),
                ),
                (
                    "story_title_ar",
                    models.CharField(
                        default="الأناقة تبدأ بالتفاصيل.",
                        max_length=180,
                        verbose_name="عنوان القصة بالعربية",
                    ),
                ),
                (
                    "story_title_en",
                    models.CharField(
                        default="Luxury lives in the details.",
                        max_length=180,
                        verbose_name="Story title in English",
                    ),
                ),
                (
                    "story_description_ar",
                    models.TextField(
                        default="بنينا PERFUME ليكون تجربة تسوق بسيطة وحديثة لعشاق العطور. نركز على جودة العرض، سهولة الاستخدام، وتنظيم المنتجات بطريقة واضحة.",
                        verbose_name="وصف القصة بالعربية",
                    ),
                ),
                (
                    "story_description_en",
                    models.TextField(
                        default="PERFUME is designed as a clean, modern shopping experience for fragrance lovers, focused on presentation, usability and carefully organized products.",
                        verbose_name="Story description in English",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="product",
            name="description_en",
            field=models.TextField(
                blank=True, default="", verbose_name="Description in English"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="name_en",
            field=models.CharField(
                blank=True, default="", max_length=200, verbose_name="Name in English"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="description",
            field=models.TextField(verbose_name="الوصف بالعربية"),
        ),
        migrations.AlterField(
            model_name="product",
            name="name",
            field=models.CharField(max_length=200, verbose_name="الاسم بالعربية"),
        ),
        migrations.RunPython(add_initial_english_product_copy, migrations.RunPython.noop),
    ]
